### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [Rostammahabadi/mod_0_skills#1]
@Rostammahabadi overall, nice work on this. There are a few updates I'd like for you to make before we consider you `technical ready`.

* [ ] Change your ingredient string attribute from class 1 to an array called ingredients
* [ ] Change your class 1 example object to reflect those changes
  * [ ] Show how it would effect your add_ingredient and remove_ingredient methods

**Comment by Rostammahabadi** [comment]
@damwhit I have updated the files accordingly, please let me know if there's anything I missed or still need to update. Thank you!

**Comment by damwhit** [comment]
@Rostammahabadi please take a bit more time to update both your class 1 and class 1 example object file per my instructions above. And let me know when you feel good about your answer.

**Comment by Rostammahabadi** [comment]
@damwhit I changed the array to state ingredients (since it has more than one) and the methods to reflect the array. However I didn't change the methods to plural as the customer can still add a singular ingredient.

**Comment by damwhit** [comment]
@Rostammahabadi I like the change in naming. And I think that being able tor remove or add a single ingredient makes a lot of sense. The remove_ingredient data update makes sense to me in your example object file. But the add_ingredient does not. Why?

**Comment by damwhit** [comment]
(pay attention to the data your attribute is starting with)

**Comment by Rostammahabadi** [comment]
@damwhit I didn't know what else is an ingredient for a steak but after some research, people use rosemary as an ingredient for steaks and it seems to fit the same category as the data which the attribute started with

**Comment by damwhit** [comment]
@Rostammahabadi not worried about the culinary validity so much in this case. The point I'm trying to get at is if we start with an array of two things. And we have a method that is supposed to add to that array, what should be the resulting array from that method?

**Comment by Rostammahabadi** [comment]
@damwhit sorry about that, I got it now! I added the ingredient to the array

**Comment by damwhit** [comment]
@Rostammahabadi looks good now! You are officially `technical ready`!
